client/src/components/Header/Header.js, client/src/components/Info/Info.js, client/src/components/Info/Info.scss, client/src/components/Login/Login.scss, client/src/components/Login/LoginForm/LoginForm.js, client/src/containers/HomeContainer/HomeContainer.js, client/src/containers/HomeContainer/HomeContainer.scss
Add routes to info chapter on home page and added info component to a home page
=> add info buttons on home page

server/controllers/user.js, server/middleware/admin.js, server/middleware/check-auth.js, server/models/user.js, server/routes/user.js
Fix User Routes, Controller, Middleware
=> Fix User controller, admin middleware and add status user

app.js, server/controllers/category.js, server/controllers/subcategory.js, server/controllers/theme.js, server/controllers/user.js, server/middleware/student.js, server/middleware/teacher.js, server/models/category.js, server/models/subcategory.js, server/models/theme.js, server/models/user.js, server/routes/category.js, server/routes/student.js, server/routes/subcategory.js, server/routes/teacher.js, server/routes/theme.js, server/routes/user.js
Added edit functionality and description for model(cat, subcat, theme)
=> Added edit functionality and description for model(cat, subcat, theme)

package-lock.json, package.json, server/config/mailer.js, server/controllers/user.js, server/mailer/mailer.js, server/models/user.js, server/routes/user.js
=> added mailer varify email

server/controllers/category.js, server/controllers/subcategory.js, server/routes/category.js, server/routes/subcategory.js
Added routes for subcategories_of_category and themes_of_subcategory
=> Added routes for subcategories_of_category and themes_of_subcategory

package-lock.json, package.json, server/controllers/user.js, server/routes/user.js
=> Added functional forgotten password

client/src/actions/verifyAction.js, client/src/components/Header/Header.js, client/src/components/SignUp/SignUp.js, client/src/components/SignUp/SignUpForm/SignUpForm.js, client/src/components/SignUp/SignUpForm/SignUpForm.scss, client/src/containers/HomeContainer/HomeContainer.js, client/src/routes/ErrorComponent.js, client/src/routes/routes.js, server/controllers/user.js, server/models/user.js, server/models/user_verify.js, server/routes/user.js
=> Added Error Page

server/controllers/user.js, server/models/user_verify.js, server/routes/user.js
=> Added Verify Account

server/controllers/user.js
=> Fix Verify Account

server/controllers/user.js
=> Fixed  Verify Account

client/src/actions/signupActions.js, client/src/components/SignUp/SignUp.js, client/src/components/SignUp/SignUpConfirmEmail/SignUpConfirmEmail.js, client/src/components/SignUp/SignUpConfirmEmail/SignUpConfirmEmail.scss, client/src/components/SignUp/SignUpForm/SignUpForm.js, client/src/reducers/signupReducer.js, client/src/routes/routes.js, server/controllers/subcategory.js, server/controllers/theme.js, server/controllers/user.js, server/middleware/check-auth.js, server/routes/admin.js
=> Added ConfirmEmail Page

server/controllers/course.js, server/controllers/user.js, server/routes/user.js
=> Added get users courses

server/controllers/course.js
=> Fix course cover edit

server/controllers/course.js, server/controllers/user.js, server/routes/course.js
=> Added delete course

server/controllers/subcategory.js, server/controllers/theme.js, server/controllers/user.js, server/routes/course.js
Fixed subcategory, theme deleted and change user controller
=> Fixed subcategory, theme deleted and change user controller

server/controllers/course.js, server/controllers/school.js, server/routes/course.js, server/routes/school.js
Added get all school list and refactoring code course controller
=> Added get all school list and refactoring code course controller

server/controllers/category.js, server/controllers/course.js, server/controllers/school.js, server/controllers/user.js, server/models/comment.js, server/models/school.js, server/routes/course.js, server/routes/school.js
Added course_get, school_get by id and refactoring code
=> Added course_get, school_get by id and refactoring code

server/controllers/search.js, server/routes/search.js
=> Added cities filter

server/controllers/course.js, server/controllers/school.js
Added url for school and course on edit functions
=> Added url for school and course on edit functions

server/controllers/course.js, server/controllers/school.js, server/routes/course.js, server/routes/school.js
Added user get course collection, school collection
=> Added user get course collection, school collection

server/controllers/course.js, server/routes/course.js
Added delete course from collection
=> Added delete course from collection

server/controllers/course.js, server/controllers/school.js, server/routes/course.js, server/routes/school.js
Added delete school from collection
=> Added delete school from collection

server/controllers/course.js, server/controllers/school.js
Fix adding course, school to collection(added multiple adding)
=> Fix adding course, school to collection(added multiple adding)

server/controllers/course.js, server/routes/course.js
=> Added get courses by theme

server/controllers/search.js, server/routes/school.js, server/routes/search.js
=> Added filter school by city

server/controllers/search.js
=> Fix filter school by city

server/controllers/course.js, server/controllers/theme.js, server/models/theme.js
Fix create theme(added url) and get courses by theme
=> Fix create theme(added url) and get courses by theme

.gitignore, app.js, server/config/keys.js, server/config/mailer.js, server/config/prod.js, server/controllers/course.js, server/controllers/search.js, server/controllers/user.js, server/routes/search.js
=> Added config files

server/controllers/course.js, server/controllers/school.js
Fixed user adding school, course to collection(back-end)
=> Fixed user adding school, course to collection

client/src/components/UI/Templates/CourseElement/CourseElement.js, server/controllers/user.js
Added check subscribe to course(client) and Fix user controller
=> Added check subscribe to course and Fix user controller

app.js
=> Fix app.js

app.js, server/controllers/user.js
Fix user controller and app.js
=> Fix user controller and app.js

app.js, server/controllers/user.js
=> Change user controller

app.js
=> Fix app.js(+/api/)
